export const AWARD_CATEGORIES_2026 = [
  "Account 2 Account Payment Processor of the Year",
  "Payment Innovator of the Year",
  "Pay-Out Innovator of the Year",
  "B-A-A-S Innovator of the Year",
  "Payment Acquirer of the Year",
  "Startup of the Year",
  "Woman Entrepreneur in FinTech of the Year",
  "Anti-Fraud Innovator of the Year",
  "ID Verification Innovator of the Year",
  "FinTech of the Year",
  "Compliance Innovator of the year",
  "Best in Customer Service MSB of the Year",
  "Remittance Innovator MSB of the Year",
  "Progressive Money Exchanger MSB of the Year",
  "MSB of the Year",
  "MSB Disruptor of the Year",
  "MSB App of the Year",
  "MSB Store of the Year",
  "MSB Global of the Year",
  "FinTech Global of the Year",
];
