const LOGO_DIR = "/assets/img/attendee-logos";

export const ATTENDEE_CATEGORIES = [
  { category: "Banking", subtitle: "Banks, FX, treasury and infrastructure leaders" },
  { category: "Open Banking", subtitle: "API-first innovators and open finance enablers" },
  { category: "Payments", subtitle: "Processors, gateways, issuing and acquiring players" },
  { category: "Card Acquirers", subtitle: "Merchant acquiring and card payment specialists" },
  { category: "Payout Companies", subtitle: "Cross-border payout and remittance partners" },
  { category: "Identity Verification", subtitle: "KYC, AML and digital identity solutions" },
  { category: "Others", subtitle: "Industry partners shaping the wider ecosystem" },
];

/*
 * Display order is the order below — keep it alphabetical as supplied by the BFA team.
 * logo: null renders the company name as a text card until an asset is supplied.
 * dark: logo artwork needs a black card. tall: stacked logo that needs extra height.
 */
export const ATTENDEE_LOGOS = [
  { name: "3ribe", category: "Others", logo: "/assets/img/discussionpanel-2026/3ribe-logo-alt.png" },
  { name: "Axcess Merchant Services", category: "Card Acquirers", logo: `${LOGO_DIR}/axcessms.com logo13.png` },
  { name: "Baaz Money", category: "Others", logo: `${LOGO_DIR}/baaz-money.png` },
  { name: "Bank of London", category: "Banking", logo: `${LOGO_DIR}/Frame.png` },
  { name: "Belyfted", category: "Others", logo: `${LOGO_DIR}/belyfted.png` },
  { name: "Blue Nile", category: "Others", logo: `${LOGO_DIR}/Blue-Nile-Money.png` },
  { name: "Chrisborough Group", category: "Payout Companies", logo: `${LOGO_DIR}/chrisborough.png` },
  { name: "Clear Junction", category: "Banking", logo: `${LOGO_DIR}/clear-junction.png` },
  { name: "Complyport", category: "Others", logo: `${LOGO_DIR}/COMPLYPORT_Logo.png` },
  { name: "Disbuz", category: "Payments", logo: `${LOGO_DIR}/disbuz.png` },
  { name: "ECEX Group", category: "Others", logo: `${LOGO_DIR}/ecex.png` },
  { name: "Ecommpay", category: "Payments", logo: `${LOGO_DIR}/ecommpay.png` },
  { name: "Emerchantpay", category: "Card Acquirers", logo: `${LOGO_DIR}/Emarchantpay.png` },
  { name: "Endoz", category: "Payments", logo: `${LOGO_DIR}/endoz.png` },
  { name: "Fena", category: "Open Banking", logo: `${LOGO_DIR}/fena.png` },
  { name: "Finest Pay", category: "Payments", logo: `${LOGO_DIR}/finestpay.png` },
  { name: "Flex Instant Pay", category: "Payments", logo: `${LOGO_DIR}/flexpay-instant-cropped.png` },
  { name: "GBG", category: "Identity Verification", logo: `${LOGO_DIR}/gbg.png` },
  { name: "GCC Exchange", category: "Payout Companies", logo: `${LOGO_DIR}/Group 2.png` },
  { name: "Glory & Honour", category: "Others", logo: `${LOGO_DIR}/GLory.png` },
  { name: "IFEPay", category: "Others", logo: `${LOGO_DIR}/ifepay.png` },
  { name: "IFX Payments", category: "Banking", logo: `${LOGO_DIR}/IFX.svg` },
  { name: "Invictus", category: "Payments", logo: "/assets/img/discussionpanel-2026/Invictus-Logo-cropped.png" },
  { name: "Kani", category: "Payments", logo: `${LOGO_DIR}/kani.png` },
  { name: "K Money", category: "Others", logo: `${LOGO_DIR}/k-money.png` },
  { name: "Kmbal", category: "Payments", logo: `${LOGO_DIR}/kmbal.png` },
  {
    name: "FOREN. formerly Leatherback",
    category: "Banking",
    logo: `${LOGO_DIR}/FOREN-formerly-LEATHERBACK.svg`,
    tall: true,
    foren: true,
  },
  { name: "Leftover Currency", category: "Others", logo: `${LOGO_DIR}/leftover-cuurency.png` },
  { name: "LinkFX", category: "Others", logo: `${LOGO_DIR}/link-fx.png` },
  { name: "Lumine Solicitors", category: "Others", logo: `${LOGO_DIR}/lumine-solicitors.png` },
  { name: "Mercury Danati", category: "Others", logo: "/assets/img/discussionpanel-2026/MercuryDanati-white.png" },
  { name: "Muthoot Global", category: "Others", logo: `${LOGO_DIR}/muthoot.png` },
  { name: "MyRemit", category: "Others", logo: `${LOGO_DIR}/my-reemit.png` },
  { name: "NEC Money", category: "Others", logo: `${LOGO_DIR}/nec-money.png` },
  { name: "Open Banking", category: "Open Banking", logo: "/assets/img/discussionpanel/OBL_logotype_darkblu-Large.png" },
  { name: "Orbital", category: "Banking", logo: `${LOGO_DIR}/orbital.png` },
  { name: "Payceler", category: "Payments", logo: `${LOGO_DIR}/payceler.png` },
  { name: "Peratera", category: "Payments", logo: "/assets/img/keynote-speakers-2026/Peratera-logo-black.png" },
  { name: "PURSE BAAS", category: "Banking", logo: `${LOGO_DIR}/purse-baas.png` },
  { name: "QF Remit", category: "Others", logo: `${LOGO_DIR}/QF-remit.png` },
  { name: "Red Sea Money Transfer", category: "Others", logo: `${LOGO_DIR}/redsea.png` },
  { name: "Sends", category: "Payments", logo: `${LOGO_DIR}/sends.png` },
  { name: "Sumsub", category: "Identity Verification", logo: `${LOGO_DIR}/sumsub 1.png` },
  { name: "Super Transfer", category: "Others", logo: `${LOGO_DIR}/super-transfer.png` },
  { name: "Teeparam", category: "Others", logo: `${LOGO_DIR}/Teeparam.png`, tall: true },
  { name: "Thunes", category: "Payments", logo: `${LOGO_DIR}/thunes-logo-dark.svg` },
  { name: "Tigris Pay", category: "Others", logo: `${LOGO_DIR}/Tigrispay.png`, tall: true },
  { name: "Transfer Rocket", category: "Others", logo: `${LOGO_DIR}/rocket-transfer.png` },
  { name: "Travel Cashier", category: "Others", logo: `${LOGO_DIR}/travel-cashier.png` },
  { name: "Trust Payments", category: "Card Acquirers", logo: `${LOGO_DIR}/trustpayments.com logo11.png` },
  { name: "University of Bristol", category: "Others", logo: `${LOGO_DIR}/Bristol.png` },
  { name: "Volume", category: "Open Banking", logo: `${LOGO_DIR}/volume.png` },
];
